modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"

issueTrackerURL="https://github.com/verySmolBrain/fantasy/issues"
[[mods]] 
modId="fantasy"
version="${file.jarVersion}"
displayName="Fantasy"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# logoFile="fantasy.png" #optional
credits="Thanks for this mod goes to Dango"
authors="Dango"

description='''
Basic fantasy mod!
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
